using AK.CoreDomain.Ads;

namespace AK.Services
{
	/// <summary>
	/// Result of an ad show operation. Returned by IAdsService.ShowAdAsync.
	/// </summary>
	public struct AdResult
	{
		/// <summary>
		/// Whether the ad was shown and completed successfully.
		/// For rewarded ads, this means the user earned the reward.
		/// </summary>
		public bool Success;

		/// <summary>
		/// The placement ID that was requested.
		/// </summary>
		public string PlacementId;

		/// <summary>
		/// The type of ad that was shown.
		/// </summary>
		public AdType AdType;

		/// <summary>
		/// Human-readable failure reason if Success is false. Null on success.
		/// </summary>
		public string FailureReason;

		/// <summary>
		/// The ad error type for programmatic handling.
		/// </summary>
		public AdErrorType ErrorType;

		/// <summary>
		/// For rewarded ads: whether the reward was actually granted (per the network's reward
		/// callback). Never inferred from the ad type - providers must report the real outcome,
		/// otherwise a user closing the ad early would still receive the reward.
		/// </summary>
		public bool RewardGranted;

		/// <summary>
		/// The ad network that served this ad (e.g., "AdMob", "Unity Ads").
		/// </summary>
		public string NetworkName;

		/// <summary>
		/// Revenue generated by this ad (if available, for analytics).
		/// </summary>
		public double Revenue;

		public static AdResult Succeeded(string placementId, AdType adType, string networkName = null, double revenue = 0, bool rewardGranted = false) => new()
		{
			Success = true,
			PlacementId = placementId,
			AdType = adType,
			FailureReason = null,
			ErrorType = AdErrorType.None,
			RewardGranted = rewardGranted,
			NetworkName = networkName,
			Revenue = revenue
		};

		public static AdResult Failed(string placementId, AdType adType, AdErrorType errorType, string reason) => new()
		{
			Success = false,
			PlacementId = placementId,
			AdType = adType,
			FailureReason = reason,
			ErrorType = errorType,
			RewardGranted = false,
			NetworkName = null,
			Revenue = 0
		};

		/// <summary>
		/// Result for when ads are disabled (e.g., user purchased "Remove Ads").
		/// </summary>
		public static AdResult AdsDisabled(string placementId, AdType adType) => new()
		{
			Success = false,
			PlacementId = placementId,
			AdType = adType,
			FailureReason = "Ads are disabled for this user",
			ErrorType = AdErrorType.AdsDisabled,
			RewardGranted = false,
			NetworkName = null,
			Revenue = 0
		};
	}

	/// <summary>
	/// Result of an ad preload operation.
	/// </summary>
	public struct AdLoadResult
	{
		/// <summary>
		/// Whether the ad was loaded successfully.
		/// </summary>
		public bool Success;

		/// <summary>
		/// The placement ID that was loaded.
		/// </summary>
		public string PlacementId;

		/// <summary>
		/// The type of ad that was loaded.
		/// </summary>
		public AdType AdType;

		/// <summary>
		/// Failure reason if Success is false.
		/// </summary>
		public string FailureReason;

		/// <summary>
		/// Error type for programmatic handling.
		/// </summary>
		public AdErrorType ErrorType;

		public static AdLoadResult Succeeded(string placementId, AdType adType) => new()
		{
			Success = true,
			PlacementId = placementId,
			AdType = adType,
			FailureReason = null,
			ErrorType = AdErrorType.None
		};

		public static AdLoadResult Failed(string placementId, AdType adType, AdErrorType errorType, string reason) => new()
		{
			Success = false,
			PlacementId = placementId,
			AdType = adType,
			FailureReason = reason,
			ErrorType = errorType
		};
	}

	/// <summary>
	/// Categorized error types for ad operations.
	/// </summary>
	public enum AdErrorType
	{
		None = 0,

		/// <summary>Ad is not ready/loaded yet.</summary>
		NotReady,

		/// <summary>Network connectivity issue.</summary>
		NetworkError,

		/// <summary>No fill from ad network.</summary>
		NoFill,

		/// <summary>User cancelled the ad (closed before completion).</summary>
		UserCancelled,

		/// <summary>Ad failed to show due to internal error.</summary>
		InternalError,

		/// <summary>Ad service is not initialized.</summary>
		NotInitialized,

		/// <summary>Invalid placement ID or configuration.</summary>
		InvalidPlacement,

		/// <summary>Frequency cap reached for this placement.</summary>
		FrequencyCapReached,

		/// <summary>Cooldown period has not elapsed.</summary>
		CooldownActive,

		/// <summary>Ads are disabled (e.g., purchased "Remove Ads").</summary>
		AdsDisabled,

		/// <summary>Ad type not supported by provider.</summary>
		UnsupportedAdType,

		/// <summary>Unknown or unclassified error.</summary>
		Unknown
	}
}